// src/features/authSlice.js
import { createSlice } from '@reduxjs/toolkit';
import { commonApiCall, createExtraReducer } from '../../utils/helper';

// Define the initial state for the signup feature
const initialState = {
    data: [],
    status: "idle", // to track loading, success, or failure state
    error: null,    // to store any error from the API
    response: null
};

// Async action to call the API for signup
export const loginUser = commonApiCall('login/loginUser', 'login', false) // thunkName | apiName | auth
export const adminlogin = commonApiCall('login/adminloginUser', 'adminlogin', false) // thunkName | apiName | auth

// Create a slice for signup
const loginSlice = createSlice({
    name: 'loginSlice',
    initialState,
    reducers: {
        setloginForm(state, action) {
            state.data = action.payload;
          },
          clearLoginForm(state) {
            state = initialState;
          },
    
    },
    extraReducers: (builder) => {
        createExtraReducer(builder, loginUser)
        createExtraReducer(builder, adminlogin)
    },
});

// Export the actions generated by the slice
export const { setloginForm, clearLoginForm } = loginSlice.actions;

// Export the reducer to be included in the store
export default loginSlice.reducer;
